### ISSUE TITLE
I cannot install the plugin

### ISSUE THREAD

**Issue by joined72** [pschw/InAppReview#1]
Hi, I cannot install the plugin, "InAppReviewPlugin.7z" file is missing and the ".gdap" and ".aar" files seems to be wrong or out of sync.

Please help me!

**Comment by pschw** [comment]
Hi,

it seems I forgot to make a release.
The files can now be downloaded under the release tab.

The zipped gdap file points to the release aar.
If your are targeting debug make sure to edit the gdap file.

Feel free to open another ticket In case of further issues.

**Comment by ayremon** [comment]
Thank you, but I have found another little bug.

You have to rename the following files:
ReviewPlugin-release.aar
ReviewPlugin-debug.aar
to
ReviewPlugin.release.aar
ReviewPlugin.debug.aar

**Comment by pschw** [comment]
Thank you!

Took me a while to do it but I appreciated your feedback.
I would have never noticed otherwise.

**Comment by ayremon** [comment]
You're welcome! ;)
